<?php

namespace App\Constants;

class Constants
{
    // Event Type
    const ENTITLEMENT_CREATION_REQUESTED = 'ENTITLEMENT_CREATION_REQUESTED';
    const ENTITLEMENT_ACTIVATION_REQUESTED = 'ENTITLEMENT_ACTIVATION_REQUESTED';
    const ENTITLEMENT_ACTIVE = 'ENTITLEMENT_ACTIVE';
    const ENTITLEMENT_PLAN_CHANGE_REQUESTED = 'ENTITLEMENT_PLAN_CHANGE_REQUESTED';
    const ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL = 'ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL';
    const ENTITLEMENT_PLAN_CHANGED = 'ENTITLEMENT_PLAN_CHANGED';
    const ENTITLEMENT_PLAN_CHANGE_CANCELLED = 'ENTITLEMENT_PLAN_CHANGE_CANCELLED';
    const ENTITLEMENT_CANCELLED = 'ENTITLEMENT_CANCELLED';
    const ENTITLEMENT_PENDING_CANCELLATION = 'ENTITLEMENT_PENDING_CANCELLATION';
    const ENTITLEMENT_CANCELLATION_REVERTED = 'ENTITLEMENT_CANCELLATION_REVERTED';
    const ENTITLEMENT_DELETED = 'ENTITLEMENT_DELETED';

    const ENTITLEMENTS = [
        self::ENTITLEMENT_CREATION_REQUESTED,
        self::ENTITLEMENT_ACTIVATION_REQUESTED,
        self::ENTITLEMENT_ACTIVE,
        self::ENTITLEMENT_PLAN_CHANGE_REQUESTED,
        self::ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL,
        self::ENTITLEMENT_PLAN_CHANGED,
        self::ENTITLEMENT_PLAN_CHANGE_CANCELLED,
        self::ENTITLEMENT_CANCELLED,
        self::ENTITLEMENT_PENDING_CANCELLATION,
        self::ENTITLEMENT_CANCELLATION_REVERTED,
        self::ENTITLEMENT_DELETED,
    ];
}
